dist: xenial
sudo: required

language: generic

services:
  - docker

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script: shellcheck install.sh

    - stage: test
      # No need to test portainer.
      before_install:
        - mv ddev-files/docker-compose.portainer.yaml ddev-files/docker-compose.portainer.yaml.dis
      install:
        - ./install.sh ci
      before_script: chmod +x tests/run-tests.sh
      script:
        - ./tests/run-tests.sh
