dist: xenial
sudo: required

language: minimal

services:
  - docker

env:
  - DDEV_VERSION=v1.4.1

before_install:
  - docker --version
  - docker-compose --version

install:
  - curl -fSL "https://github.com/drud/ddev/releases/download/$DDEV_VERSION/ddev_docker_images.$DDEV_VERSION.tar.gz" -o ddev.tar.gz
  - tar -xzf ddev.tar.gz -C /tmp/ && chmod ugo+x /tmp/ddev
  - sudo mv /tmp/ddev /usr/local/bin

script:
  - bash install.sh
